Get http://localhost:5029/accounts
###

Get http://localhost:5029/accounts/2

###
Post http://localhost:5029/accounts
Content-Type: application/json

{
    "UserName": "BurakOzsubasi",
    "Password": "password",
    "Email":"burak@example.com",
    "IpAddress":"111.222.111",
    "CategoryId": 1
}

###
Put http://localhost:5029/accounts/1
Content-Type: application/json

{
    "UserName": "BurakOzsubasi",
    "Password": "password",
    "Email":"burak@example.com",
    "IpAddress":"111.222.111"
}

###

DELETE http://localhost:5029/accounts/1